
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
#    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: "Namank@1234"
#    password: "afyJoLSoUVEegqCVyOxlDopUdMtrFIPS"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or 'create', 'validate', 'none' depending on your use case
    show-sql: true


#Suggestion: Let's use environment variables for DB URL, username, and password.
#  It will improve security and allow every developer to run the project locally
#  without changing configuration files




#server:
#  port: ${PORT:8080}
#
#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect