
server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ehr_db
    username: root
    password: 9006894885
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    user:
      name: user
      password: krishna
jwt:
  secret: c7f75eaa04c8749f73a74496b669a862f00bba7033e0a8e8279f6b3d7f1be2c9
  expiration: 86400000
  refresh-expiration: 604800000

